export const AUTH_KEY_SIGN_IN_PENDING = 'AUTH_KEY_SIGN_IN_PENDING';
export const AUTH_KEY_SIGN_IN_SUCCESS = 'AUTH_KEY_SIGN_IN_SUCCESS';
export const AUTH_KEY_SIGN_IN_ERROR = 'AUTH_KEY_SIGN_IN_ERROR';
export const AUTH_KEY_SIGN_IN_RESET = 'AUTH_KEY_SIGN_IN_RESET';

export const AUTH_KEY_SIGN_UP_PENDING = 'AUTH_KEY_SIGN_UP_PENDING';
export const AUTH_KEY_SIGN_UP_SUCCESS = 'AUTH_KEY_SIGN_UP_SUCCESS';
export const AUTH_KEY_SIGN_UP_ERROR = 'AUTH_KEY_SIGN_UP_ERROR';
export const AUTH_KEY_SIGN_UP_RESET = 'AUTH_KEY_SIGN_UP_RESET';

export const AUTH_KEY_SIGN_OUT_PENDING = 'AUTH_KEY_SIGN_OUT_PENDING';
export const AUTH_KEY_SIGN_OUT_SUCCESS = 'AUTH_KEY_SIGN_OUT_SUCCESS';
export const AUTH_KEY_SIGN_OUT_ERROR = 'AUTH_KEY_SIGN_OUT_ERROR';
export const AUTH_KEY_SIGN_OUT_RESET = 'AUTH_KEY_SIGN_OUT_RESET';