export const ACTIVE_COUNTRY_LIST_PENDING = 'ACTIVE_COUNTRY_LIST_PENDING';
export const ACTIVE_COUNTRY_LIST_SUCCESS = 'ACTIVE_COUNTRY_LIST_SUCCESS';
export const ACTIVE_COUNTRY_LIST_ERROR = 'ACTIVE_COUNTRY_LIST_ERROR';
export const ACTIVE_COUNTRY_LIST_RESET = 'ACTIVE_COUNTRY_LIST_RESET';

export const PAY_COUNTRY_NETWORK_PENDING = 'PAY_COUNTRY_NETWORK_PENDING';
export const PAY_COUNTRY_NETWORK_SUCCESS = 'PAY_COUNTRY_NETWORK_SUCCESS';
export const PAY_COUNTRY_NETWORK_ERROR = 'PAY_COUNTRY_NETWORK_ERROR';
export const PAY_COUNTRY_NETWORK_RESET = 'PAY_COUNTRY_NETWORK_RESET';

export const COUNTRY_BY_DIAL_CODE_PENDING = 'COUNTRY_BY_DIAL_CODE_PENDING';
export const COUNTRY_BY_DIAL_CODE_SUCCESS = 'COUNTRY_BY_DIAL_CODE_SUCCESS';
export const COUNTRY_BY_DIAL_CODE_ERROR = 'COUNTRY_BY_DIAL_CODE_ERROR';
export const COUNTRY_BY_DIAL_CODE_RESET = 'COUNTRY_BY_DIAL_CODE_RESET';