
export const DETAIL_RESTAURANT_LIST_PENDING = 'DETAIL_RESTAURANT_LIST_PENDING';
export const DETAIL_RESTAURANT_LIST_SUCCESS = 'DETAIL_RESTAURANT_LIST_PENDING';
export const DETAIL_RESTAURANT_LIST_ERROR = 'DETAIL_RESTAURANT_LIST_PENDING';
export const DETAIL_RESTAURANT_LIST_RESET = 'DETAIL_RESTAURANT_LIST_PENDING';


export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SELECT_DISH = 'SELECT_DISH';
export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';
export const ADD_FAVORITE_ITEM = 'ADD_FAVORITE_ITEM';
export const REMOVE_FAVORITE_ITEM = 'REMOVE_FAVORITE_ITEM';



